-- local lint = require('lint')
--
-- local checkpatch_path = vim.loop.cwd() .. '/scripts/checkpatch.pl'
--
-- vim.api.nvim_create_autocmd({ "BufWritePost" }, {
--   callback = function()
--     require("lint").try_lint()
--   end,
-- })
--
-- lint.linters_by_ft = {
--   c = {}
-- }
--
-- if (vim.fn.filereadable(checkpatch_path)) then
--   lint.linters.checkpatch.cmd = checkpatch_path
--   lint.linters_by_ft.c[#lint.linters_by_ft.c+1] = "checkpatch"
-- end
--
vim.g.checkpatch_path = vim.loop.cwd() .. "/scripts/checkpatch.pl"
