# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [
    # "xhci_pci"
    #
    # # NVMe
    # "nvme"
    #
    # # SD cards and internal eMMC drives.
    # "mmc_block"
  ];
  
  boot.initrd.kernelModules = [
    # Rockchip modules
    # "rockchip_rga"
    # "rockchip_saradc"
    # "rockchip_thermal"
    # "rockchipdrm"

    # GPU/Display modules
    # "analogix_dp"
    # "cec"
    # "drm"
    # "drm_kms_helper"
    # "dw_hdmi"
    # "dw_mipi_dsi"
    # "gpu_sched"
    # "panel_edp"
    # "panel_simple"
    # "panfrost"
    # "pwm_bl"

    # USB / Type-C related modules
    # "fusb302"
    # "tcpm"
    # "typec"

    # Misc. modules
    # "cw2015_battery"
    # "gpio_charger"
    # "rtc_rk808"
  ];
  # boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";
}
