set nocompatible              " be iMproved, required
filetype off                  " required

"Vundle
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'

"Themes
Plugin 'flazz/vim-colorschemes'

"Git
Plugin 'tpope/vim-fugitive'

"Languages server
Plugin 'w0rp/ale'

"Rust
Plugin 'rust-lang/rust.vim'

"Code
Plugin 'sheerun/vim-polyglot'
Plugin 'tomtom/tcomment_vim'

"Tools
Plugin 'vim-airline/vim-airline'

call vundle#end()            " required
filetype plugin indent on    " required

"General
syntax on
set path=$PWD/**
set number
set cursorline 
set wildmenu
set cc=80

"Indentation
set autoindent
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab

"Theme
set background=dark
set t_ut=

"Plugin
let g:ale_linters_explicit = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_insert_leave = 0
let g:ale_linters = {}

""Dev
"C
let g:ale_linters.c = ['clangd']

"Rust
let g:ale_linters.rust = ['rls']
let g:rustfmt_autosave = 1
