# Dock
xrandr --auto &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Ssh
eval $(ssh-agent)

# NetworkManager
nm-applet &

# Redshift
redshift -l 48.84:2.35

# Keyboard
setxkbmap us -option caps:escape &

# Dm
exec i3
